In [1]:
import jax
import jax.numpy as jnp

In [2]:
from LIMxCMBL.init import *


In [3]:
# Lambda_idx = int(sys.argv[1])
# nbins = int(sys.argv[2])
# ell_idx = int(sys.argv[3])

Lambda_idx = 18
nbins = 100

Lambda = Lambdas[Lambda_idx]

# CCAT-prime
zmin = 3.5
zmax = 8.1

oup_fname = '/scratch/users/delon/LIMxCMBL/I_auto/comb'
oup_fname += '_zmin_%.1f_zmax_%.1f_Lambda_idx_%d_nb_%d_jax.npy'%(zmin, zmax, Lambda_idx, nbins)
print(oup_fname)

/scratch/users/delon/LIMxCMBL/I_auto/comb_zmin_3.5_zmax_8.1_Lambda_idx_18_nb_100_jax.npy


In [4]:
Omega_field = 8 * (np.pi/180)**2 #rad^2
Pei = 2.3e4 #Mpc^3 kJy^2 /sr^2 
chimin = ccl.comoving_angular_distance(cosmo, 1/(1+zmin))
chimax = ccl.comoving_angular_distance(cosmo, 1/(1+zmax))

In [5]:
from scipy.interpolate import interp1d, LinearNDInterpolator
from scipy.integrate import quad, quad_vec, trapezoid, tplquad

inner_dkparp_integral = np.load('LIMxCMBL/inner_dkparp_integral.npy')
tmp_chibs = []
tmp_log_deltas = []
tmp_fnctn = []
for i in range(len(chibs)):
    for j in range(len(deltas)):
        tmp_chibs += [chibs[i]]
        tmp_log_deltas += [np.log10(deltas[j])]
        tmp_fnctn += [inner_dkparp_integral[:,i,j]]
        
f_inner_integral = LinearNDInterpolator(list(zip(tmp_chibs, tmp_log_deltas)), tmp_fnctn)
f_inner_integral_LoLo = interp1d(x = chibs, y = inner_dkparp_integral, axis = 1)

In [6]:
inner_dkparp_integral.shape

(100, 256, 128)

In [7]:
from interpax import interp2d, interp1d
inner_dkparp_integral = np.moveaxis(inner_dkparp_integral, [0,1,2], [2,0,1])
print(inner_dkparp_integral.shape)
inner_dkparp_integral = jnp.array(inner_dkparp_integral.astype(np.float64))

(256, 128, 100)


In [8]:
f_inner_integral((7838, np.log10(0.001)))

array([7.52789430e+02, 7.53677751e+02, 7.54637646e+02, 7.55672991e+02,
       7.56787517e+02, 7.57984717e+02, 7.59267738e+02, 7.60639235e+02,
       7.62101205e+02, 7.63654832e+02, 7.65300305e+02, 7.67036579e+02,
       7.68861100e+02, 7.70769452e+02, 7.72755076e+02, 7.74808880e+02,
       7.76918816e+02, 7.79069426e+02, 7.81241326e+02, 7.83410668e+02,
       7.85548579e+02, 7.87620536e+02, 7.89585741e+02, 7.91396524e+02,
       7.92997694e+02, 7.94325987e+02, 7.95309590e+02, 7.95867771e+02,
       7.95910696e+02, 7.95339538e+02, 7.94046896e+02, 7.91917717e+02,
       7.88830703e+02, 7.84660582e+02, 7.79281068e+02, 7.72568865e+02,
       7.64408751e+02, 7.54699746e+02, 7.43362411e+02, 7.30346923e+02,
       7.15641865e+02, 6.99282815e+02, 6.81360160e+02, 6.62024577e+02,
       6.41488863e+02, 6.20023961e+02, 5.97946678e+02, 5.75593866e+02,
       5.53274567e+02, 5.31389699e+02, 5.10217842e+02, 4.89842814e+02,
       4.70142244e+02, 4.50810230e+02, 4.31425206e+02, 4.11553485e+02,
      

In [9]:
inner_dkparp_integral.shape

(256, 128, 100)

In [10]:
interp2d(xq = [7838], yq=[np.log(0.001)], 
         x = chibs, y = np.log(deltas), f=inner_dkparp_integral,
        method='linear',)

Array([[7.5279883e+02, 7.5368726e+02, 7.5464716e+02, 7.5568250e+02,
        7.5679694e+02, 7.5799426e+02, 7.5927722e+02, 7.6064874e+02,
        7.6211066e+02, 7.6366425e+02, 7.6530975e+02, 7.6704602e+02,
        7.6887061e+02, 7.7077899e+02, 7.7276459e+02, 7.7481842e+02,
        7.7692834e+02, 7.7907898e+02, 7.8125079e+02, 7.8342023e+02,
        7.8555811e+02, 7.8763000e+02, 7.8959534e+02, 7.9140613e+02,
        7.9300726e+02, 7.9433563e+02, 7.9531921e+02, 7.9587738e+02,
        7.9592041e+02, 7.9534930e+02, 7.9405670e+02, 7.9192749e+02,
        7.8884058e+02, 7.8467059e+02, 7.7929102e+02, 7.7257886e+02,
        7.6441882e+02, 7.5470990e+02, 7.4337262e+02, 7.3035718e+02,
        7.1565216e+02, 6.9929321e+02, 6.8137067e+02, 6.6203510e+02,
        6.4149951e+02, 6.2003461e+02, 5.9795740e+02, 5.7560461e+02,
        5.5328534e+02, 5.3140063e+02, 5.1022885e+02, 4.8985385e+02,
        4.7015347e+02, 4.5082159e+02, 4.3143671e+02, 4.1156506e+02,
        3.9012241e+02, 3.6654800e+02, 3.4052823e

In [11]:
chi_bin_edges = jnp.linspace(chimin*(1+1e-8), chimax*(1 - 1e-8), nbins + 1)
chi_bin_centers = (chi_bin_edges[1:] + chi_bin_edges[:-1])/2
dchi_binned = jnp.mean(jnp.diff(chi_bin_edges))

In [12]:
from jax import jit

In [13]:
_tmp = np.load('LIMxCMBL/_KI.npy')
_chis, _KI = _tmp[0], _tmp[1]

In [14]:
_chis = jnp.array(_chis)
_KI = jnp.array(_KI)

In [15]:
@jit
def f_KILo(chi, external_chi, Lambda):
    return (Lambda / jnp.pi 
            * jnp.interp(x = chi, xp = _chis, 
                         fp = _KI, left = 0, right = 0) 
            * jnp.sinc(Lambda * (external_chi - chi) / np.pi))

@jit
def f_integrand(_chib, chip, chi):
    # by assumption chimin <= chi,chip <= chimax
    #I Lo
    _delta = jnp.abs(1 - chi/_chib) #(1)
    _delta = jnp.where(_delta < 1e-6, 1e-6, _delta)
    _delta = jnp.where(_delta > 0.7, 0.7, _delta)
    c1    = jnp.where(chimin <= (2*_chib - chi), 
            jnp.where((2*_chib - chi) <= chimax, 
            jnp.where(chimin <= chi, 
            jnp.where(chi <= chimax,
                2 * jnp.interp(x = chi, xp = _chis, fp = _KI, left = 0, right = 0) 
                * interp2d(xq = _chib, yq=jnp.log(_delta), 
                           x = chibs, y = jnp.log(deltas), f=inner_dkparp_integral,
                           method='linear',) #
                / (_chib**2) 
                * f_KILo(2*_chib - chi, external_chi = chip, Lambda=Lambda),
                      0),0),0),0)
    _delta = jnp.abs(1 - chip/_chib) #(1)
    _delta = jnp.where(_delta < 1e-6, 1e-6, _delta)
    _delta = jnp.where(_delta > 0.7, 0.7, _delta)

    c2    = jnp.where(chimin <= (2*_chib - chip), 
            jnp.where((2*_chib - chip) <= chimax, 
            jnp.where(chimin <= chip, 
            jnp.where(chip <= chimax,
                2 * jnp.interp(x = chip, xp = _chis, fp = _KI, left = 0, right = 0)
                * interp2d(xq = _chib, yq=jnp.log(_delta), 
                           x = chibs, y = jnp.log(deltas), f=inner_dkparp_integral,
                           method='linear',)
                / (_chib**2)
                * f_KILo(2*_chib - chip, external_chi = chi, Lambda=Lambda),
                      0),0),0),0)

    cross_integrand = c1+c2
    
    #LoLo
    plus = _chib*(1+deltas) #(d)
    mins = _chib*(1-deltas) #(d)
    _idxs = (chimin < plus) & (plus < chimax) & (chimin < mins) & (mins < chimax)
    LoLo_integrand  = jnp.where(_idxs,
                               f_KILo(plus, external_chi = chi, Lambda=Lambda) 
                                * f_KILo(mins, external_chi = chip, Lambda=Lambda),
                               0) #(d)
    LoLo_integrand += jnp.where(_idxs,
                               f_KILo(mins, external_chi = chi, Lambda=Lambda) 
                                * f_KILo(plus, external_chi = chip, Lambda=Lambda),
                               0) #(d)
    
    LoLo_integrand *= (2 / _chib) #(d)
    LoLo_integrand *= deltas
    LoLo_integrand = jnp.einsum('d, dl->ld',
                                LoLo_integrand,
                                interp1d(xq = _chib,
                                         x = chibs, f=inner_dkparp_integral,
                                         method='linear',))           
    
    LoLo_integrand = jnp.trapezoid(x = jnp.log(deltas), y = LoLo_integrand, axis=-1)
    return LoLo_integrand - cross_integrand

In [16]:
f_integrand(8000, 8001, 8004)

Array([-6.6355819e-09, -6.6383814e-09, -6.6414092e-09, -6.6446759e-09,
       -6.6481927e-09, -6.6519688e-09, -6.6560131e-09, -6.6603327e-09,
       -6.6649295e-09, -6.6698047e-09, -6.6749544e-09, -6.6803660e-09,
       -6.6860251e-09, -6.6919075e-09, -6.6979782e-09, -6.7041910e-09,
       -6.7104908e-09, -6.7168009e-09, -6.7230306e-09, -6.7290666e-09,
       -6.7347767e-09, -6.7399952e-09, -6.7445343e-09, -6.7481674e-09,
       -6.7506356e-09, -6.7516384e-09, -6.7508341e-09, -6.7478343e-09,
       -6.7422072e-09, -6.7334707e-09, -6.7210983e-09, -6.7045192e-09,
       -6.6831261e-09, -6.6562817e-09, -6.6233334e-09, -6.5836279e-09,
       -6.5365389e-09, -6.4814900e-09, -6.4179906e-09, -6.3456755e-09,
       -6.2643442e-09, -6.1740049e-09, -6.0749143e-09, -5.9676086e-09,
       -5.8529173e-09, -5.7319465e-09, -5.6060432e-09, -5.4766800e-09,
       -5.3452824e-09, -5.2134901e-09, -5.0826534e-09, -4.9531717e-09,
       -4.8244519e-09, -4.6949591e-09, -4.5624868e-09, -4.4246105e-09,
      

In [17]:
from quadax import quadgk, quadcc

In [18]:
@jit
def chib_quad(y, x, L, R):
    return quadgk(f_integrand, [L, R],
                  epsabs = 0.0, epsrel = 1e-3, 
                  args=(y, x))[0]

chib_quad(8080,8080, chimin, chimin*(1+1e-1));

In [19]:
@jit
def bin_j_quad(x, lj, L, rj, R):
    return quadgk(chib_quad, [lj, rj],
                  epsabs = 0.0, epsrel = 1e-3, 
                  args=(x, L, R))[0]

bin_j_quad(8080, 8080, chimin, 8081, chimin*(1+1e-1));

In [20]:
@jit
def bin_i_quad(li, lj, L, ri, rj, R):
    return quadgk(bin_j_quad, [li, ri],
                  epsabs = 0.0, epsrel = 1e-3, 
                  args=(lj, L, rj, R))[0]

In [21]:
i = 13
li, ri = chi_bin_edges[i], chi_bin_edges[i+1]

j = 14
lj, rj = chi_bin_edges[j], chi_bin_edges[j+1]


In [ ]:
res = bin_i_quad(li, lj, 10, ri, rj, chimax_sample)

In [ ]:
res / dchi_binned**2

In [ ]:
from tqdm import trange

In [ ]:
# comb_binned = np.zeros((len(ells), nbins, nbins))
# for i in range(nbins):
#     print(i+1,'/',nbins)
#     for j in trange(i, nbins):
#         li, ri = chi_bin_edges[i], chi_bin_edges[i+1]
#         lj, rj = chi_bin_edges[j], chi_bin_edges[j+1]
#         comb_binned[:, i,j], _ = bin_i_quad(li, lj, 10, ri, rj, chimax_sample)
#         comb_binned[:, i,j] /= dchi_binned**2
#         comb_binned[:, j, i] = comb_binned[:, i,j]